version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - frontend

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    image: dockersamples/examplevotingapp_vote
    container_name: vote
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - frontend

  result:
    image: dockersamples/examplevotingapp_result
    container_name: result
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - backend

  worker:
    image: dockersamples/examplevotingapp_worker
    container_name: worker
    depends_on:
      - redis
      - db
    networks:
      - frontend
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:

